const BAYER_GREEK: Record<string, string> = {
  Alp: "Alpha",
  Bet: "Beta",
  Gam: "Gamma",
  Del: "Delta",
  Eps: "Epsilon",
  Zet: "Zeta",
  Eta: "Eta",
  The: "Theta",
  Iot: "Iota",
  Kap: "Kappa",
  Lam: "Lambda",
  Mu: "Mu",
  Nu: "Nu",
  Xi: "Xi",
  Omi: "Omicron",
  Pi: "Pi",
  Rho: "Rho",
  Sig: "Sigma",
  Tau: "Tau",
  Ups: "Upsilon",
  Phi: "Phi",
  Chi: "Chi",
  Psi: "Psi",
  Ome: "Omega",
};

const CON_GENITIVE: Record<string, string> = {
  And: "Andromedae",
  Ant: "Antliae",
  Aps: "Apodis",
  Aql: "Aquilae",
  Aqr: "Aquarii",
  Ara: "Arae",
  Ari: "Arietis",
  Aur: "Aurigae",
  Boo: "Boötis",
  Cae: "Caeli",
  Cam: "Camelopardalis",
  Cap: "Capricorni",
  Car: "Carinae",
  Cas: "Cassiopeiae",
  Cen: "Centauri",
  Cep: "Cephei",
  Cet: "Ceti",
  Cha: "Chamaeleontis",
  Cir: "Circini",
  CMa: "Canis Majoris",
  CMi: "Canis Minoris",
  Cnc: "Cancri",
  Col: "Columbae",
  Com: "Comae Berenices",
  CrA: "Coronae Australis",
  CrB: "Coronae Borealis",
  Crt: "Crateris",
  Cru: "Crucis",
  Crv: "Corvi",
  CVn: "Canum Venaticorum",
  Cyg: "Cygni",
  Del: "Delphini",
  Dor: "Doradus",
  Dra: "Draconis",
  Equ: "Equulei",
  Eri: "Eridani",
  For: "Fornacis",
  Gem: "Geminorum",
  Gru: "Gruis",
  Her: "Herculis",
  Hor: "Horologii",
  Hya: "Hydrae",
  Hyi: "Hydri",
  Ind: "Indi",
  Lac: "Lacertae",
  Leo: "Leonis",
  Lep: "Leporis",
  Lib: "Librae",
  LMi: "Leonis Minoris",
  Lup: "Lupi",
  Lyn: "Lyncis",
  Lyr: "Lyrae",
  Men: "Mensae",
  Mic: "Microscopii",
  Mon: "Monocerotis",
  Mus: "Muscae",
  Nor: "Normae",
  Oct: "Octantis",
  Oph: "Ophiuchi",
  Ori: "Orionis",
  Pav: "Pavonis",
  Peg: "Pegasi",
  Per: "Persei",
  Phe: "Phoenicis",
  Pic: "Pictoris",
  PsA: "Piscis Austrini",
  Psc: "Piscium",
  Pup: "Puppis",
  Pyx: "Pyxidis",
  Ret: "Reticuli",
  Scl: "Sculptoris",
  Sco: "Scorpii",
  Sct: "Scuti",
  Ser: "Serpentis",
  Sex: "Sextantis",
  Sge: "Sagittae",
  Sgr: "Sagittarii",
  Tau: "Tauri",
  Tel: "Telescopii",
  TrA: "Trianguli Australis",
  Tri: "Trianguli",
  Tuc: "Tucanae",
  UMa: "Ursae Majoris",
  UMi: "Ursae Minoris",
  Vel: "Velorum",
  Vir: "Virginis",
  Vol: "Volantis",
  Vul: "Vulpeculae",
};

/*
 * Parses the Name field from the YBSC star catalog to extract the
 * Flamsteed number, Bayer designation, and constellation name.
 */
export default function parseStarName(name: string) {
  const match = name.trim().match(/^(\d+)([A-Za-z]+)?\s+([A-Za-z]+)$/);
  if (!match) return {};

  const [, flamsteed, bayer, constellation] = match;

  return {
    flamsteed: parseInt(flamsteed),
    bayer: bayer ? BAYER_GREEK[bayer] || bayer : null,
    constellation: CON_GENITIVE[constellation] || constellation,
  };
}
